version: '3.8'

services:
  web:
    container_name: docker_loadbalancerserver
    build: .
    ports:
      - "5400:5400"
    restart: always
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s
    env_file: ./app/env
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    # volumes:
    #   - ./storage:/storage

    depends_on:
      - cache

  cache:
    container_name: docker_redis
    image: redis:6.0-alpine
    ports: 
      - "6380:6379"

